spring:
  application:
    name: sensor
  kafka:
    bootstrap-servers: localhost:9092,localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
      properties:
        delivery:
          timeout:
            ms: 20000
        linger:
          ms: 0
        request:
          timeout:
            ms: 10000
